# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='vinitramk@gmail.com', max_length=250),
        ),
    ]
